language: python
before_install: 
 - sudo apt-get install software-properties-common
 - sudo add-apt-repository -y ppa:gijzelaar/aartfaac
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libblitz0-dev python-dev libcasacore-dev libblas-dev liblapack-dev libgdbm-dev wcslib-dev libfftw3-dev python-numpy libcfitsio3-dev
install: 
 - cd ${TRAVIS_BUILD_DIR}
 - mkdir build && cd build
 - cmake ..
 - make
 - make install
script: 
 - true
